Add missing dependency
And fix generic-common to latest that works here.

This codebase needs a class from spring-ldap

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/home/thrantal/.m2/repository/fi/vm/sade/generic/generic-common/9.4-SNAPSHOT/generic-common-9.4-SNAPSHOT.jar!/fi/vm/sade/security/CustomUserDetailsMapper.class]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/security/ldap/userdetails/LdapUserDetailsMapper.class] cannot be opened because it does not exist

because it CustomUserDetailsMapper depends on that.
And as omatsivut depends on hakemus-api that uses
AbstractPermissionService that is removed in generic-common
version 9.7-SNAPSHOT, we should upgrade first port
hakemus-api to work with the latest generic-common code so
we could upgrade it.